"""User: change notification fields name.

Revision ID: 0f12ddecac06
Revises: 
Create Date: 2024-08-02 16:24:43.896793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f12ddecac06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receive_comment_notification', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receive_follow_notification', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receive_collect_notification', sa.Boolean(), nullable=True))
        batch_op.drop_column('receive_follow_notifications')
        batch_op.drop_column('receive_collect_notifications')
        batch_op.drop_column('receive_comment_notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receive_comment_notifications', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('receive_collect_notifications', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('receive_follow_notifications', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('receive_collect_notification')
        batch_op.drop_column('receive_follow_notification')
        batch_op.drop_column('receive_comment_notification')

    # ### end Alembic commands ###
