"""add admin theme

Revision ID: 375ed29be5ed
Revises: 
Create Date: 2024-07-25 13:41:59.735247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375ed29be5ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
